spring.application.name=06.sb-configs
ticket.pnr=AAF4563R

#jdbc.driverClass=com.mysql.cj.jdbc.Driver
#jdbc.url=jdbc:mysql://localhost:3306/dbbb_wipro
#jdbc.userName=root
#jdbc.password=root

driverClass=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://localhost:3306/dbbb_wipro
userName=root
password=root