spring.application.name=09.sb-banner-app

logging.file.name= logs/log.txt
logging.level.root = info

#spring.main.banner-mode=console
#spring.main.banner-mode=off
spring.main.banner-mode=log
spring.banner.location=myBanner.txt
